name: Release
on:
  create:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build Binary
        run: export Version=$env:GITHUB_REF_NAME && make build

      - name: Tar
        run: make tar

      - name: Create Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: codegen.tar.gz
          file_glob: true
